### PR TITLE
Add p.me aws deploy doc

### PR DESCRIPTION
**Pull request by secret104278**

### CODE REVIEW

**Comment by chhsiao1981** [comment]
need to clean up pme.zip before merge.

**Comment by chhsiao1981** [comment]
@secret104278 

What's the expected input of the following prompt in setup_aws_ssh.sh?

echo -n "Enter your application URL: "
read env_url
echo

**Comment by secret104278** [comment]
> @secret104278
> 
> What's the expected input of the following prompt in setup_aws_ssh.sh?
> 
> echo -n "Enter your application URL: "
> read env_url
> echo

After the deployment of the AWS EB, you will get an URL, which is the domain name point to your ec2 instance.
For example, `mypme-env-1.3jpmvexi8u.us-east-1.elasticbeanstalk.com`
https://imgur.com/xg8l4di

**Comment by chhsiao1981** [comment]
another issue is that the deployment is allowed only within tokyo-region.

**Comment by secret104278** [comment]
The region parameter is just a default value.
Users can still chose the region in the web console https://imgur.com/sJGgsAR

**Comment by secret104278** [comment]
> The region parameter is just a default value.
> Users can still chose the region in the web console https://imgur.com/sJGgsAR

**Comment by secret104278** [comment]
> another issue is that the deployment is allowed only within tokyo-region.

The region parameter in the url is just a default value.
Users can still chose whatever they want in web console https://imgur.com/sJGgsAR

**Comment by chhsiao1981** [comment]
@secret104278 

1. I am not sure where to exec ./setup_aws_ssh.sh
2. need to setup docker port mapping as 0.0.0.0:9487->9487, 127.0.0.1:9774 -> 9774/tcp, 127.0.0.1:14779 -> 14779/tcp (-p 9487:9487 -p 127.0.0.1:9774:9774 -p 127.0.0.1:14779:14779)
3. need to have 9774 / 14779 / 9487 open to the public in the securitygroup.config.

**Comment by chhsiao1981** [comment]
1. maybe no need for setup_aws_ssh.sh
2. no need to setup docker port mapping. use aws security-group to allow only port 22.

**Pull request merged**
